### ISSUE TITLE
Cannot find the assembly 'Facebook, Version=4.10.0.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by aparnatiwari30** [CrossGeeks/FacebookClientPlugin#41] opened 2019-03-28 12:40 UTC
I have update the FacebookClientPlugin to version 1.4.0. And now android app is building fine but iOS App build is getting fail with below message
  
```
MTOUCH : warning MT0136: Cannot find the assembly 'Facebook, Version=4.10.0.0, Culture=neutral, PublicKeyToken=null' referenced from '/Users/…./packages/Plugin.FacebookClient.1.4.0/lib/Xamarin.iOS10/Plugin.FacebookClient.dll'.
MTOUCH : error MT2001: Could not link assemblies. Reason: Error while processing references of 'xxxx.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
Done building target "_CompileToNative" in project “xxxx.iOS.csproj" -- FAILED.
```

Version Number of Plugin:1.4.0
Version of VS: 7.8.2
Version of Xamarin: 3.1

**Comment by ColdThor** [comment] 2019-04-08 13:49
I´m having the same issue, have you solved it yet?

**Comment by rdelrosario** [comment] 2019-08-31 17:38
Can't reproduce this issue but if still having it please test:

https://www.nuget.org/packages/Plugin.FacebookClient/2.0.1-beta

If not fixed in this version please re-open.

**Closed by rdelrosario** 2019-08-31 17:38 UTC
